---
title: "Defining Concepts"
subtitle: POSC 3410  -- Quantitative Methods in Political Science
author: Steven V. Miller
institute: Department of Political Science
titlegraphic: /Dropbox/teaching/clemson-academic.png
date: 
output:
 beamer_presentation:
    template: ~/Dropbox/miscelanea/svm-r-markdown-templates/svm-latex-beamer.tex
    latex_engine: xelatex
    dev: cairo_pdf
    fig_caption: true
    slide_level: 3
make149: true
mainfont: "Open Sans"
titlefont: "Titillium Web"
---

# Introduction
### Goal for Today

*Introduce students to clarifying, identifying, and defining concepts.*




# Concepts and Operationalization
### Concepts in Politics

Concepts pervade discussion about politics in all facets.

- The U.S. flexes its "power" in the international system.
- "Corruption" is rampant in several post-Soviet states.
- American politics is beset with problems of "polarization" and "partisanship."
- The "developing" world is replete with failed attempts at "democratization."
- Somalia and Afghanistan are examples of "failed states."
- "Democracies" have never fought a "war" against each other.
- "Old school racism" was replaced by "racial resentment" after the Civil Rights movement.

These are just examples.

### What Are Concepts?

**Concepts** are ideas of mental constructs that represent phenomena in the real world.

- We can't sense them (e.g. see, taste, smell), per se.
- They can be simple (e.g. partisanship) or complicated (e.g. corruption).
- They are *not* value-laden.

### What Are Concepts?

Concepts intuitively vary among units in the real world.

- The U.S. is more "powerful" than Nicaragua.
- Kazakhstan is more "corrupt" than Norway.
- Canada is more democratic than Angola.

### Variation in the Real World

This leads to questions we want to answer:

- Why is Western Europe more "peaceful" than South Asia?
- Why are some Americans "intolerant" of social and political difference?
- How is "partisanship" increasing in the U.S.?

### Conceptual and Concrete Questions

**Conceptual questions** are expressed using ideas and are hard to answer.

\bigskip

It's better to to ask **concrete questions.**

- These carry with it a priori beliefs about what "counts" as the concept in question.

### Asking Concrete Questions

Here's a toy example: are women more "liberal" than men?

- This is definitely answerable, provided we have a definition of "liberal."

A **conceptual definition** describes the concept's measurable properties and units of analysis.

- From there, we create an **operational definition** of actually implementing the conceptual definition.


### Defining "Liberalism"

Consider this definition: "Liberalism is the extent to which individuals support increased government spending for social programs."

- It takes vague idea of "liberalism" and refers to measurable attribute of social spending.
- Use of “the extent to which” notes that this attribute varies across unit.
- More support for social spending should coincide with "more liberalism."
- It also specifies a unit of analysis: people.

## Clarifying Concepts
### Clarifying Liberalism

There are three problems in clarifying concepts.

1. Defining a concept with another concept.
2. Defining a concept with unmeasurable attributes.
3. Treating multi-dimensional concepts as unidimensional.

### Clarifying Liberalism

What comes to mind when we think of "liberalism" in American politics?

- This is naturally juxtaposed with "conservatism."

Long story short: who looks like a "liberal" and who looks like a "conservative?"

### Images of Liberals and Conservatives

| **Liberal** | **Conservative** |
|:-------------|:------------------|
| Has low income | Has high income |
| Is younger | Is older |
| Supports social justice | Opposes social justice |
| Opposes free market | Supports free market |
| Supports government-sponsored health care | Opposes government-sponsored health care |
| Opposes tax cuts | Supports tax cuts |
| Opposes abortion restrictions | Supports abortion restrictions |
| Supports same-sex marriage | Opposes same-sex marriage |

Do note this brainstorming is an open-ended process.

### Problems with These Images

Prima facie, these "sound about right." 

- However, our task is to put a concept into operation, not stereotype.

Think of the first two components: income and age.

- Is being young and/or poor really part of "liberalism?"
- Can we think of what it means to be "liberal" without these?

The answer should be a clear "yes."

- Don't misunderstand: age and income clearly correlate with liberalism.
- However they are not themselves "liberal" values.

### Condensed Images of Liberals and Conservatives

| **Liberal** | **Conservative** |
|:-------------|:------------------|
| Supports social justice | Opposes social justice |
| Opposes free market | Supports free market |
| Supports government-sponsored health care | Opposes government-sponsored health care |
| Opposes tax cuts | Supports tax cuts |
| Opposes abortion restrictions | Supports abortion restrictions |
| Supports same-sex marriage | Opposes same-sex marriage |

Are we satisfied with these?

### More Problems with These Images

Prima facie, these also "sound about right." 

- However, we need to be more discerning.

The first two of these condensed images do not belong. Why?

### More Problems with These Images


1. They're not immediately measurable.
2. These include abstract concepts---e.g. "free market", "social justice"---that demand further clarification.

If you can only "know it when you see it" (a la Potter Stewart), then you must dig deeper.


### Further Condensed Images of Liberals and Conservatives

| **Liberals** | **Conservatives** |
|:-------------|:------------------|
| Supports government-sponsored health care | Opposes government-sponsored health care |
| Opposes tax cuts | Supports tax cuts |
| Opposes abortion restrictions | Supports abortion restrictions |
| Supports same-sex marriage | Opposes same-sex marriage |

Now are we done?

### More Problems with These Images

Once more, these also "sound about right."

- But we have a new issue.

These inventory items seem to cluster naturally into **conceptual dimensions.**

- The first two refer to government spending.
- The second two refer to social issues.

In short, we have a **multimensional concept**, which are common in political science.

- Examples: democracy (norms, institutions), socioeconomic status (income, occupation, education)

## Units of Analysis
### Units of Analysis

All conceptual dimensions specify a **unit of analysis** (i.e. the entity we want to describe). We generally have two levels that interest us:

- Individual-level (e.g. citizens, Congressmen)
- Aggregate-level (e.g. classrooms, districts, states, countries)

Concepts can be applicable to both levels.

- Example: we can feasibly think of "liberal" voters and "liberal" states.

### Beware the Ecological Fallacy

An **ecological fallacy** is a classic inferential problem.

- This is the use of aggregate-level information to make inferences at the individual-level.
- You can think of this as a form of stereotyping.

Examples of ecological fallacies in political science:

- Immigrants have lower literacy rates, but areas with a lot of immigrants have higher literacy rates.
- Rich voters tend to be Republican. Rich states tend to be Democratic.

# Conclusion
### Conclusion

Our interest in politics is driven by an interest in certain phenomena.

- However, take care to make clear your concepts of these phenomena.

Concepts need to communicate several things.

- Measurable attributes within the concept itself.
- Variation implicit within the concept itself.
- A unit of analysis to which the concept applies.