---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Dropbox/miscelanea/svm-r-markdown-templates/svm-latex-syllabus.tex
geometry: margin=1in
title: "POSC 3410: Quantitative Methods in Political Science"
author: Steven V. Miller
email: "svmille@clemson.edu"
web: "svmiller.com/teaching"
date: "Spring 2016"
officehours: "W 09:00-11:30 a.m."
office: "230A Brackett Hall"
classhours: "TR 02:00-03:15 p.m."
classroom: "233 Brackett Hall"
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
# keywords: "pandoc, r markdown, knitr"
# bibliography: ~/Dropbox/master.bib
---

# Course Description

Both students and scholars alike are in political science as a result of their keen interest in politics. However, there is an increasing gap between how political science is applied by scholars and how it is understood by students. This class will aim to bridge that gap by introducing students to the *science* of political science. We will start with the basics, discussing concepts and variables before advancing toward regression. The course will conclude with very basic introductions to some advanced topics like non-normal responses, Bayesian inference, and post-estimation simulation. The overall goal of this class is to prepare students for upper division courses where peer-reviewed journal articles with multiple regressions and/or formal models are prominent.

# Course Objectives

1. Understand concepts and how we operationalize abstract concepts for the sake of testing.

2. Delineate variables among various types, like nominal, ordinal and interval.

3. Put together a formal research design to address questions of interest in the study of politics.

4. Express why the logic of control is vital to any good research design.

5. Understand important elements of data, like central tendency and spread.

6. Become familiar with advanced topics like non-normal responses, Bayesian thinking, and post-estimation simulation.

# Required Readings

- Pollock III, Philip H. 2012. *The Essentials of Political Analysis* (4th edition). Washington DC: CQ Press.
- Lynch, Scott M. 2013. *Using Statistics in Social Research: A Concise Approach*. Springer.

# Course Policies

This section of the syllabus details multiple policies that will be implemented in this class through the semester. Continuation in this class constitutes acceptance of the terms outlined in this document.

## Grading Policy

- **20%** of your grade will be determined by a midterm to be administered on **Thursday, February 11** during normal class hours. There will be **NO** make-ups.

- **20%** of your grade will be determined by three problem sets (i.e. homework) to be due periodically through the semester. The prospectus will be graded as an additional problem set as well.

- **10%** of your grade will be determined by your attendance and participation in class.

- **20%** of your grade will be determined by a research design paper that applies quantitative methodology to a social science question of interest. I provide more information about this paper in a supplemental document on my course website. This research design is due **Friday, April 22, before 9:00 a.m.** It must be submitted via *Turnitin* on the course’s Blackboard module.

- **30%** of your grade will be determined by a final exam. Clemson University has scheduled this final exam on **Thursday, April 28, 08:00-10:30 a.m.** There will be **NO** make-ups.

## Homework ("Lab") Policy

I assign problem sets that require a rudimentary knowledge of the `R` programming language. Students should download this free software programming language at [cran.r-project.org](http://cran.r-project.org) and install it on their personal computer.

- The `R` scripts I provide are designed to work on the student’s computer with minimal maintenance. I will make this clear in each particular script.

- I *strongly* encourage students to meet with me in office hours to learn about the language. I will assume that not meeting with me means the student is fluent with the software.

- Consider getting a graphical user interface (GUI) front-end for `R` to learn it better. I recommend Rstudio, available for free at [www.rstudio.com](http://www.rstudio.com).

## In-Class Policy

- **Attendance**: I will take attendance every class. Students are allocated **five** unexcused absences. Upon the sixth unexcused absence, the student receives 0% of the attendance grade for the class. Students have one week after a missed class to provide documentation excusing the absence in class. I will *not* inform students, even upon request, about how many unexcused absences they have through the semester. I only tabulate that information near the end of the semester when I am finalizing grades.

- **Participation**: I want to reward each student in the class with all the participation and attendance points. If I suspect students are not doing the reading and not volunteering answers to questions posed by me in class, I will resort to cold-calling students from a list. Failure to answer a question posed by me when cold-called from a roster of students will result in a one-point deduction of the overall grade for the semester.

- **Late Arrival of the Professor**: If, for some reason, I am more than fifteen minutes late to class, a volunteer student should check in 232 Brackett Hall with Ms. Angela Guido.  If class is cancelled, I will send an email in advance of class.

- **Make-Up Exams**: There are **NO** make-ups for missed exams. Professors are forever intolerant of weak excuses. Do not bring them to me. Missed exams in cases of illness or personal emergency can be accommodated only with proper documentation. This *does not* mean a student can punt an exam to the near future because of a headache or the sniffles, for which a medical excuse is sought several hours after missing the exam in question. I will not accept these notes. Exams missed due to a university-sponsored event or religious holiday may also be accommodated, provided that the student informs me of the conflict *at least two weeks in advance*. Students who have valid excuses, with documentation, for missing exam dates have *one week at the most* from the original date of the exam to complete a missed exam.

- **Cell Phones, Pagers, Laptops, PDAs**: Unless Student Disabilities Services informs me that such a device is a necessary accommodation for a student with disabilities, all laptops, tablets, and PDAs are to be put away during class (both in lecture and during exams). There are two reasons for this. One, you are on Facebook anyway when you are using them during class. That can wait. Two, laptops are---and I must emphasize this---[*terrible* learning devices](http://svmiller.com/blog/2014/09/taking-good-notes/). Likewise, keep your phone or pager (do people still use those?) in your bag or pocket during class. The professor reserves the right to embarrass the student for not having a phone on "vibrate" during class. If not, the ringtone better be something good.

- **Disputing an Assignment Grade**: I am willing to accommodate students who believe my grading of an assignment was too harsh or misunderstanding. Students who wish to dispute a grade on an assignment must submit a one-page, single-spaced argument for a grade change before that request is considered.

## Academic Dishonesty Policy

I take academic integrity seriously and will show no tolerance for any instances of academic dishonesty. The logic behind cheating or plagiarism may be self-interest, but this is too myopic. Penalties for being caught are severe and the consequences of being found culpable will extend well beyond the student's time as a college student at Clemson. In the interest of clarification, I provide the definitions of several types of academic dishonesty below, [as understood by Clemson University](http://www.clemson.edu/administration/student-affairs/student-handbook/universitypolicies/academic_integrity.html).  Avoid intentionally or inadvertently committing any of these acts:

- **Cheating**: Giving, receiving, or using unauthorized aid, including the inappropriate use of electronic devices, in any work submitted to fulfill academic requirements. In examination situations all electronic devices must be off and stowed unless otherwise authorized by the instructor.

- **Plagiarism**: The intentional or unintentional copying of language, structure, or ideas of another and attributing the work to one's own efforts.

- **Unlawful Access to Private Material**:  Attempts to copy, edit, or delete computer files that belong to another person or use of computer accounts that belong to another person without the permission of the file owner or account owner.

Clemson University's Academic Integrity Statement broadly defines breaches of academic integrity as "lying, cheating, or stealing in any form." This broad definition of academic integrity that will be enforced in my classroom.

## Disabilities Policy

Federal laws mandate the provision of services at the university level to qualified students with disabilities. If a student requires special provisions, I encourage that student to let me know *privately* as soon as possible (preferably within the first two weeks of the semester). Afterward, I am required to refer the student to the [Student Disabilities Services](http://www.clemson.edu/campus-life/campus-services/sds/) (SDS), which will determine the necessary provisions that I must make. SDS will give its recommendations to the student, who must relay their recommendations to me. I, as the instructor, am responsible for providing the necessary accommodations, but only at the behest of SDS. The student maintains privacy rights on the matter, which I wholeheartedly will respect. That said, *it is the student's responsibility to initiate the provision process*. This can only be done, privately and securely, through SDS.

Students who require quiet test rooms or extended time for exams must take the initiative to schedule a room at the [Test Proctoring Center](http://www.clemson.edu/campus-life/campus-services/sds/test-center.html) on campus. These rooms must be scheduled by the student for the day of the exam as listed in the syllabus. Failure by the student to schedule a room at the Test Proctoring Center for the day of the exam will lead to a zero on the assignment.

\newpage

# Class Schedule

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE)
mon <- as.Date("2016-01-04")
fri <- as.Date("2016-01-08")

advdate <- function(obj, adv) {
 tmp <- obj + 7*(adv-1)
 tmp <- format(tmp, format="%m/%d")
 return(tmp)
}

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}
```

Students must read the following before Tuesday's class session.  Important: class readings are subject to change, contingent on mitigating circumstances and the progress we make as a class.  Students are encouraged to attend lectures and check the course website for updates. All given topics coincide with chapters in Pollock III (2012) and Lynch (2013), the designated texts for the course, unless otherwise noted.

#### `r advdate(mon, 1)`: 
Syllabus Day

- No class Thursday (SPSA Conference in Puerto Rico)
- Read *all* associated documents on course website.
    - [A Beginner's Guide to Using `R`](http://svmiller.com/blog/2014/08/a-beginners-guide-to-using-r/)
    - [Reading a Regression Table: A Guide for Students](http://svmiller.com/blog/2014/08/reading-a-regression-table-a-guide-for-students/)
    - [Taking Good Notes](http://svmiller.com/blog/2014/09/taking-good-notes/)
    - [How to Do a Literature Review](http://svmiller.com/blog/2014/11/how-to-do-a-literature-review/)
    - [Dos and Dont's of Writing for Students](http://svmiller.com/blog/2015/06/dos-and-donts-of-writing-for-students/)
    - [Assorted Tips for Students on Writing Research Papers](http://svmiller.com/blog/2015/12/assorted-tips-students-research-papers/)
    - [Exam Grading Policy](https://www.dropbox.com/s/apihjs7di81aqcv/svm-exam-grading-policy.pdf?dl=0)
    - [Writing a Prospectus](https://www.dropbox.com/s/i2vzzg0vmy6ppw4/posc3410-prospectus-guide.pdf)
    - [Prospectus Example](https://www.dropbox.com/s/swrs77jawpxpec8/posc3410-prospectus-example.pdf?dl=0)
    - [Research Design Paper Instructions](https://www.dropbox.com/s/qhv4d4pjsk2rxgt/posc3410-research-design-paper-instructions.pdf?dl=0)
    

####  `r advdate(mon, 2)`: 
Introduction, the Research Process (Lynch, chp. 1-2)

####  `r advdate(mon, 3)`: 
Defining and Measuring Concepts (Pollock, chp. 1)

####  `r advdate(mon, 4)`: 
Measuring, Describing Variables (Pollock, chp. 1; Lynch, chp. 4)

- *Problem set #1 due in-class on Thursday.*

####  `r advdate(mon, 5)`: 
Explanations, Hypotheses, and Making Comparisons (Pollock, chp. 3)

####  `r advdate(mon, 6)`:  
MIDTERM

####  `r advdate(mon, 7)`: 
Probability Theory (Lynch, chp. 5)

####  `r advdate(mon, 8)`: 
Research Design, Control, and Controlled Comparisons (Pollock, chp. 4-5)

####  `r advdate(mon, 9)`: 
Statistical Inference (Lynch, chp. 6; Pollock, chp. 6)

- *Prospectus due in-class on Thursday.*
- *Problem set #2 due in-class on Thursday.*


####  `r advdate(mon, 10)`:  
Correlation and Linear Regression (Lynch, chp. 9; Pollock, chp. 8)

####  `r advdate(mon, 11)`:  
SPRING BREAK

####  `r advdate(mon, 12)`: 
NO CLASS THIS WEEK (PROFESSOR WILL BE OUT OF TOWN)

####  `r advdate(mon, 13)`: 
Regression (Continued) (Lynch, chp. 10; Pollock, chp. 9)

####  `r advdate(mon, 14)`: 
Bayesian Inference

- Western, Bruce and Simon Jackman. 1994. "Bayesian Inference for Comparative Research." *American Political Science Review* 88(2): 412-423.


####  `r advdate(mon, 15)`: 
Making the Most of Statistical Analysis

- Gelman, Andrew. 2008. "Scaling Regression Inputs by Dividing by Two Standard Deviations." *Statistics in Medicine*. 27: 2865–2873.
- King, Gary, Michael Tomz, and Jason Wittenberg. 2000. "Making the Most of Statistical Analyses: Improving Interpretation and Presentation." *American Journal of Political Science*, 44(2): 341–355.
- *Problem set #3 due in-class on Thursday.*

####  `r advdate(mon, 16)`: 
Replication

- Reinhart, Carmen M. and Kenneth S. Rogoff. 2010. "Growth in a Time of Debt." *American Economic Review* 100(2): 573-578.
- Herndon, Thomas, Michael Ash, and Robert Pollin. 2013. "Does High Public Debt Consistently Stifle Economic Growth? A Critique of Reinhart and Rogoff." *Cambridge Journal of Economics*, 38(2): 257–279.

####  `r advdate(mon, 17)`:  
FINAL EXAMS
