---
title: The Research Process
subtitle: POSC 3410 -- Quantitative Methods in Political Science
author: Steven V. Miller
date: 
fontsize: 10pt
output:
  beamer_presentation:
#    keep_tex: true
#    toc: true
    slide_level: 3
#    fig_caption: yes
    includes:
      in_header: ~/Dropbox/teaching/clemson-beamer-header-simple.txt
      after_body: ~/Dropbox/teaching/table-of-contents.txt
---

# Introduction
### Goal for Today

*Provide an overview of the research process.*

# The Research Process
### Research as a Process

Scientific research is a process that entails the following.

1. Developing an empirically answerable question.
2. Deriving a *falsifiable* hypothesis from a theory purported to answer the question.
3. Gathering/analyzing data to test the hypothesis.
4. Rejecting or failing to reject the hypothesis.
5. Relating results to theory from which the question was drawn.

## What Research is Not
### What Research is *Not*

There are three things that are not considered scientific research.

1. Reviewing literature on a topic.
2. Theory construction in the absence of empirical data.
3. Gathering data without a research question.

### Research is More than a Lit Review

A lit review is an important part of research.

- We can't go far without reviewing what we already (don't) know on a topic.

However, research entails an original contribution.

### Research is More than Theorizing

Theory-writing *is* perhaps the most important part of scientific research.

- It's a rigorous, logical process.

By itself, it's not an *empirical* process, though.

- Scientific research entails an analysis of some form of data.

### Research is Data Analysis with a Purpose

Data collection/analysis alone is not research.

- Why are the data being collected or analyzed?
- What question is being answered?
- What theory is being tested?

By this metric, even the U.S. Census can't be considered research.

- Census data is certainly used in research.
- By itself, it's not research.

## Replication as Research
### Replication as Research

Replication *is* research.

- It's the process of repeating an experiment or study to verify the original findings.
- Even your "volcano" science experiment in junior high counts as replication of centuries-old hypotheses on acids and bases.

Sadly, it's difficult to get such work published.

- Few people in political science want to hear about what we already know.
- Failures to replicate may hinge on small factors.

Still, failures to replicate all of a finding may lead to a qualification of the original findings.

## Stages of Research
### Stages of Research

1. Starting with a perspective
2. Selecting/writing a theory
3. Deriving a proposition
4. Asking a research question
5. Deriving hypotheses

These first five stages constitute the introduction, literature review, and theory section of a paper.

### Stages of Research

6. Find or collect data
7. Analyze data

These constitute the research design section of a paper.

8. Report results and answer motivating question

This is the results/analysis section of a paper.

9. Interpret results in terms of theory
10. Draw implications from theory

These become the conclusion/discussion section of a paper.

### What is a Perspective?

A perspective is a general orientation to the world. They're untestable because:

1. They're too broad. Empirical support will never be total.
2. Perspectives are slippery and contextual.
	- e.g. "Government should stay out of our lives."
3. Any empirical data observed can be interpreted to fit the perspective.

We start with perspectives because we're not blank slates.

- Perspectives inform the data collection/analysis process.

### What is a Theory?

Theories follow perspectives.

- They're systematic purported explanations of how the "world" (or part of it that interests the researcher) operates.

Theories are too abstract to be tested.

- However, they lend themselves to operationalizations of the theory's concepts.
- We end up testing the theory's predictions (or hypotheses).

### Propositions, Research Questions, Hypotheses

Other components:

- Propositions: a single, potentially testable component of a theory
- Research questions: frame a question about the proposition

	- They also suggest a way to evaluate it.
	
- Hypotheses are the *falsifiable* statements.

	- i.e. they are able to be "proven wrong".
	- They also entail a means of operationalization (i.e. variables).
	
### Summary of the Research Process

Different disciplines have different norms about this process.

- Political science has mostly moved from "grand theorizing" toward mid-level theorizing.
- The emphasis on perspectives may be more for sociology than political science.

	- Rationality (or liberalism) may be the ubiquitous perspective.
	- i.e. People/firms/states are self-interested and instrumentally rational.
	
Perhaps political science looks more like: puzzle -> research question -> theory -> hypotheses -> analysis.

- However, this streamlined process assumes a level of expertise you may not have yet.
- You may also find your original research question too broad to start.

## The Relationship between Research and Proof
### Research Does Not Prove

The research process is a deductive exercise.

- Each stage is a consequence of the previous stage.
- As a result, we can't prove theories true.
- At the most, we say our findings are consistent with the theory.

### Affirming the Consequent

Generally, our hypotheses look like forms of an argument or syllogism.

- If my theory is valid (A), my predictions about the data will be correct (B).
- If we observe B, we cannot prove A.

Take a simple logical example: if Dabo Swinney wins the lottery (A), he will be rich (B).

- Dabo Swinney is rich.
- Therefore, Dabo Swinney won the lottery.

We know this is not true.

- i.e. Swinney is rich because he's a college football coach.

### Denying the Consequent

Research can't prove a theory true, but it can disprove one.

- i.e. if A, then B. Not-B. Therefore, Not-A.

Take a simple logical example.

- If it rained (A), then my yard will be wet (B).
- My yard is not wet.
- Therefore, it didn't rain.

If the data don't support the hypothesis, you can reject all or part of the theory.

# Conclusion
### Conclusion

This lecture discussed the process of scientific investigation.

- There are some forms of inquiry that don’t qualify as research.
- There are quirks to each discipline, but the process is mostly shared across all forms of science.

As you start thinking of your projects, start thinking about what your process will look like in each stage.